# Generated by Django 2.2 on 2019-04-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JDInfo',
            fields=[
                ('title', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('price', models.URLField(default='', max_length=10)),
                ('commit', models.URLField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('ulevel', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=20)),
                ('uaddr', models.CharField(max_length=20)),
                ('ugrade', models.CharField(max_length=20)),
            ],
        ),
    ]
